/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    orders: Order;
    products: Product;
    categories: Category;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    promotions: Promotion;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('admin' | 'customer') | null;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  user?: (string | null) | User;
  items?:
    | {
        product?: (string | null) | Product;
        title?: string | null;
        price?: number | null;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  total: number;
  status?: ('pending' | 'shipped' | 'delivered') | null;
  paymentStatus?: ('unpaid' | 'paid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug: string;
  price: number;
  compareAtPrice?: number | null;
  taxable?: boolean | null;
  hasVariants?: boolean | null;
  variants?:
    | {
        option1?: string | null;
        option2?: string | null;
        option3?: string | null;
        price?: number | null;
        sku?: string | null;
        stock?: number | null;
        barcode?: string | null;
        id?: string | null;
      }[]
    | null;
  trackInventory?: boolean | null;
  stock?: number | null;
  availability?: ('inStock' | 'outOfStock' | 'preOrder') | null;
  images?: (string | Media)[] | null;
  featuredImage?: (string | null) | Media;
  categories?: (string | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  handle?: string | null;
  productType?: ('physical' | 'digital' | 'service') | null;
  digitalFile?: (string | null) | Media;
  weight?: number | null;
  customFields?:
    | (
        | {
            key?: string | null;
            value?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textField';
          }
        | {
            key?: string | null;
            value?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'numberField';
          }
        | {
            key?: string | null;
            value?: ('option1' | 'option2') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'selectField';
          }
      )[]
    | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  media?: (string | null) | Media;
  parent?: (string | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout: (
    | {
        variant: 'fullWidth' | 'split' | 'compact';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        headline: string;
        subheadline?: string | null;
        backgroundImage?: (string | null) | Media;
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        variant: 'grid' | 'list' | 'carousel';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        products?: (string | Product)[] | null;
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'listProducts';
      }
    | {
        variant: 'textOnly' | 'withImage' | 'timeline';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutUs';
      }
    | {
        variant: 'imageOnly' | 'withText' | 'fullScreen';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        items?:
          | {
              image?: (string | null) | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'carousel';
      }
    | {
        variant: 'simple' | 'highlighted' | 'boxed';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'info';
      }
    | {
        variant: 'list' | 'table' | 'summary';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        orders?: (string | Order)[] | null;
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'orders';
      }
    | {
        variant: 'simple' | 'detailed' | 'stepped';
        impactLevel?: ('low' | 'normal' | 'high') | null;
        items: {
          name: string;
          price: number;
          quantity: number;
          id?: string | null;
        }[];
        subBlocks?:
          | {
              variant: 'simple' | 'highlighted' | 'boxed';
              impactLevel?: ('low' | 'normal' | 'high') | null;
              text: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'info';
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'checkout';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        title?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  total?: T;
  status?: T;
  paymentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  price?: T;
  compareAtPrice?: T;
  taxable?: T;
  hasVariants?: T;
  variants?:
    | T
    | {
        option1?: T;
        option2?: T;
        option3?: T;
        price?: T;
        sku?: T;
        stock?: T;
        barcode?: T;
        id?: T;
      };
  trackInventory?: T;
  stock?: T;
  availability?: T;
  images?: T;
  featuredImage?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  handle?: T;
  productType?: T;
  digitalFile?: T;
  weight?: T;
  customFields?:
    | T
    | {
        textField?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        numberField?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        selectField?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  media?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        listProducts?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              products?: T;
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        aboutUs?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              content?: T;
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        info?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        orders?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              orders?: T;
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        checkout?:
          | T
          | {
              variant?: T;
              impactLevel?: T;
              items?:
                | T
                | {
                    name?: T;
                    price?: T;
                    quantity?: T;
                    id?: T;
                  };
              subBlocks?:
                | T
                | {
                    info?:
                      | T
                      | {
                          variant?: T;
                          impactLevel?: T;
                          text?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  activePromotions?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        bannerImage?: (string | null) | Media;
        startDate: string;
        endDate: string;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  colors: {
    lightMode: {
      /**
       * Primary color for light mode
       */
      primary: string;
      /**
       * Secondary color for light mode
       */
      secondary: string;
      /**
       * Accent color for light mode
       */
      accent: string;
      /**
       * Background color for light mode
       */
      background: string;
    };
    darkMode: {
      /**
       * Primary color for dark mode
       */
      primaryDark: string;
      /**
       * Secondary color for dark mode
       */
      secondaryDark: string;
      /**
       * Accent color for dark mode
       */
      accentDark: string;
      /**
       * Background color for dark mode
       */
      backgroundDark: string;
    };
  };
  favicon?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  navLinks?:
    | {
        label: string;
        type?: ('internal' | 'external') | null;
        url?: string | null;
        reference?:
          | ({
              relationTo: 'products';
              value: string | Product;
            } | null)
          | ({
              relationTo: 'categories';
              value: string | Category;
            } | null);
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    label: string;
    url: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  copyrightText: string;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  activePromotions?:
    | T
    | {
        title?: T;
        description?: T;
        bannerImage?: T;
        startDate?: T;
        endDate?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  colors?:
    | T
    | {
        lightMode?:
          | T
          | {
              primary?: T;
              secondary?: T;
              accent?: T;
              background?: T;
            };
        darkMode?:
          | T
          | {
              primaryDark?: T;
              secondaryDark?: T;
              accentDark?: T;
              backgroundDark?: T;
            };
      };
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        reference?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  copyrightText?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}